
on:
  push:
    tags:
      - 'v*'
      
name: Create Release and save notes to file

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
        - name: Run a one-line script
          run: echo Hello, world!

  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        run: |
          gh release create ${{ github.ref }} --generate-notes
          echo "hello!"
          gh api -H "Accept: application/vnd.github+json" /repos/anna-follestad-4ss/auto-release/releases/latest 
          echo "hello again!"
          echo ""
          gh api -H "Accept: application/vnd.github+json" /repos/anna-follestad-4ss/auto-release/releases/latest -q ".body"
          echo "hello again!"
          echo ""
           gh api -H "Accept: application/vnd.github+json" /repos/anna-follestad-4ss/auto-release/releases/latest -q ".body" > docs/new_notes.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Git
        run: |
          git config user.name 'anna-follestad-4ss'
          git config user.email 'anna.fehn.follestad@4subsea.com'
 
      - name: Push latest version
        run: |
          git commit -m "initial commit"
          git push origin main --tags
      
          

        
