# This is a basic workflow to help you get started with Actions

name: Get release notes

# Controls when the workflow will run
on:
  workflow_dispatch:
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:           
  Get_release:   
    runs-on: windows-latest 
    
    steps:
      - name: Check out source
        uses: actions/checkout@v3
      
      - name: get the release
        run: |
          gh api /repos/anna-follestad-4ss/auto-release/releases/latest --jq '.[].body'
          gh api /repos/anna-follestad-4ss/auto-release/releases/latest --jq '.[].id'
          gh api /repos/anna-follestad-4ss/auto-release/releases/latest --jq '.[].assets_url'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
     


