on:
  workflow_dispatch:
    inputs:
      milestoneId:
        description: 'Milestone ID'     
        required: true
        default: '1'
        
name: Milestone Closure - release notes generator 
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.access_token }}
        
    - uses: actions/checkout@master
    - name: Create Release Notes
      uses: docker://decathlon/release-notes-generator-action:2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.access_token }}
        OUTPUT_FOLDER: temp_release_notes
        USE_MILESTONE_TITLE: "false"
        milestoneID: '2'
