on:
  milestone:
    types: [closed]
  workflow_dispatch:
    inputs:
      milestoneId:
        description: 'Milestone ID'     
        required: true
        default: '1'
        
name: Milestone Closure - generate notes
jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Release notes generator
        uses: Decathlon/release-notes-generator-action@v3.1.6

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #USE_MILESTONE_TITLE: "true"
          FILENAME: "my_custom_file"
          milestoneId: '5'
