# This is a basic workflow to help you get started with Actions

name: Write to file

# Controls when the workflow will run
on:
  workflow_dispatch:
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:           
  write:   
    runs-on: windows-latest 
    
    steps:
      - name: Check out source
        uses: actions/checkout@v3
      
      - name: add some text
        run: |
          chdir docs
          cat release_notes.rst
          echo "pause"
          x='echo "even More Text"' # ; cat release_notes.rst'
          echo "$x" > release_notes.rst
      
      - name: Setup Git
        run: |
          git config user.name 'anna-follestad-4ss'
          git config user.email 'anna.fehn.follestad@4subsea.com'
        
      - name: Push latest version
        run: |
          git add docs/release_notes.rst
          git commit -m "added some text to release notes"
          git push origin main

