# This is a basic workflow to help you get started with Actions

name: Write to file

# Controls when the workflow will run
on:
  workflow_dispatch:
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:           
  write:   
    runs-on: windows-latest 
    
    steps:
      - name: Check out source
        uses: actions/checkout@v3
      
      - name: create dir
        run: |
          mkdir mydirname
          chdir mydirname
          echo "this is some text" > randomtext.txt


      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    x=`echo "Name: John"; cat mydirname/my_file.txt`
      #    echo "$x" > mydirname/my_file.txt
      - name: Push latest version
        run: |
        git add mydirname/randomtext.txt
        git commit -m "added some file"
        git push origin main

