# This is a basic workflow to help you get started with Actions

name: Write to file

# Controls when the workflow will run
on:
  workflow_dispatch:
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:           
  #write:   
  #  runs-on: windows-latest 
  #  
  #  steps:
  #    - name: Check out source
  #      uses: actions/checkout@v3
#
 #     - name: third text adder
  #      id: add_more_text
  #      run: |
  #        chdir docs
  #        echo "my new release notes v2" > new_notes.txt
  #        type release_notes.rst >> new_notes.txt
  #        type new_notes.txt > release_notes.rst
       
  #    - name: Setup Git
  #      run: |
  #        git config user.name 'anna-follestad-4ss'
  #        git config user.email 'anna.fehn.follestad@4subsea.com'
  #      
  #    - name: Push latest version
  #      run: |
  #        git add docs/release_notes.rst
  #        git commit -m "added some text to release notes"
  #        git push origin main
          
  write-ubuntu:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out source
        uses: actions/checkout@v3
        with:
          ref: main
          
      - name: ubuntu text adder
        run: |
          cd docs
          sed -i "3 i \ " release_notes.rst
          sed -i '3 r new_notes.txt' release_notes.rst
          sed -i "3 i ------------------------------------------------" release_notes.rst
          sed -i '3 i What is new in version X.Y.Z og Dato 2 ' release_notes.rst
          sed -i "3 i \ " release_notes.rst
  
  
      - name: Setup Git
        run: |
          git config user.name 'anna-follestad-4ss'
          git config user.email 'anna.fehn.follestad@4subsea.com'
        
      - name: Push latest version
        run: |
          git add docs/release_notes.rst
          git commit -m "added some text to release notes"
          git push origin main

